
CREATE TABLE [dbo].[CallTypesDim](
	[CallType_ID] [int] IDENTITY(1,1) NOT NULL,
	[CallTypeShort] [nvarchar](50) NOT NULL,
	[CallTypeName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK__CallType__D2F0E18055C06DBA] PRIMARY KEY CLUSTERED 
(
	[CallType_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


